#!/bin/sh

email=${1}

msg(){
cat << EOS

Congratulations, and welcome to Google Mail.

Now that you have successfully opted in, all messages sent to your $email@onid.orst.edu email address and $email@onid.oregonstate.edu email address will arrive here and will no longer be delivered to ONID Webmail. Email clients such as Thunderbird, Mac Mail, or Outlook may still be used, but they must be reconfigured.

For help using Google Mail, go to:

  http://oregonstate.edu/helpdocs/software/google-apps-osu/google-mail
EOS
}

msg | bin/sendEmail -q -o reply-to=no-reply@oregonstate.edu -f no-reply@oregonstate.edu -u 'Welcome to Google Mail' -f no-reply@oregonstate.edu -t ${1}@onid.oregonstate.edu -s smtp.oregonstate.edu
