#!/bin/sh

msg(){
cat << EOS
You have successfully opted in to Google Mail! All messages sent to your ONID email address will now be delivered to Google Mail.

Your next steps...

 - Login to your Google Mail account at http://oregonstate.edu/google to verify your email is working properly.
 
 - Read the welcome email delivered to your new Google Mail inbox for important information and next steps.
EOS
}

msg | bin/sendEmail -q -o reply-to=no-reply@oregonstate.edu -f no-reply@oregonstate.edu -u 'ONID Email Opt-In Complete' -f no-reply@oregonstate.edu -t ${1}@onid.oregonstate.edu -s smtp.oregonstate.edu
