#!/bin/sh

msg(){
cat << EOS

<p>Congratulations, and welcome to Google Mail! Now that you have migrated, all messages sent to your ${1}@onid.orst.edu email address and ${1}@onid.oregonstate.edu email address will arrive here and will no longer be delivered to ONID Webmail. Email clients such as Thunderbird, Mac Mail, or Outlook may still be used, but they must be reconfigured (see #1 below).</p>

<p>For more information on how to use Google Mail, we encourage you to visit the Google learning center at <a href="http://learn.googleapps.com/gmail">http://learn.googleapps.com/gmail</a>.</p>

<p><b>Your next steps and where to go for help</b></p>

<p>The following OSU Helpdocs give you more tips and tricks for using Google Mail.</p>

<p>Configurations
<ul>
    <li><a href="">Configure Email Forwarding in Google Mail</a></li>
    <li><a href="">Configure Your Mobile Apps</a></li>
    <li><a href="">Configure Desktop Mail Clients</a></li>
</ul>
</p>

<p>General Tips
<ul>
    <li><a href="">Directory and Contacts - What’s the difference?</a></li>
    <li><a href="">Google Mail Trash (automatically purges data after 30 days)</a></li>
</ul>
</p>
EOS
}

msg | bin/sendEmail -q -o reply-to=no-reply@oregonstate.edu -f no-reply@oregonstate.edu -u 'Subject: ONID email now migrated to Google Mail!' -f no-reply@oregonstate.edu -t ${1}@onid.oregonstate.edu -s smtp.oregonstate.edu
