#!/bin/sh

PATH=$PATH:/vol/goblin/bin

msgSendmail(){
cat << ESO
REPLY-To: OSU Google Project Team <no-reply@oregonstate.edu>
Organization: Oregon State University
MIME-Version: 1.0
Subject: Account Migration to Google Mail in Progress

ESO
msg
}

msg(){
cat << EOS
Your ONID email migration is in progress. Please watch for the opt-in completion notice.

EOS
}

msgSendmail | /usr/lib/sendmail -f no-reply@oregonstate.edu ${1}@onid.oregonstate.edu
