#!/bin/sh

PATH=$PATH:/vol/goblin/bin

msgSendmail(){
cat << ESO
REPLY-To: PSU Google Project Team <no-reply@pdx.edu>
Organization: Portland State University
MIME-Version: 1.0
Subject: Account Migration to PSU Google Mail in Progress

ESO
msg
}

msg(){
cat << EOS
Your migration to PSU Google Mail has begun!  Please read the 
following important items:

1. Your access to Google Mail has been enabled in order to complete 
the migration process, but it is VERY important that you do not use 
Google Mail until you receive notification that the process is complete.  
Using Google Mail before the migration is complete could cause email 
messages to be permanently erased.

2. During this process, you can continue to use your current mail setup.  
The migration typically takes between 10 minutes and 1 hour to complete, 
but can take up to 48 hours.   You will receive a final email in your 
PSU mailbox when the migration has finished along with your next steps.

3. Email clients (i.e. Thunderbird, Outlook, and iPhone/Android mail apps) 
will not work correctly and need to be reconfigured once the migration 
process is complete.  Links to instructions for configuring email clients 
will be included in the completion notification sent to your new 
Google Mail account.

4. Email forwarding (if configured in OAM or Webmail) will stop, and 
any existing mail filters & rules will need to be re-configured in Google Mail.  
Links to instructions for configuring email forwarding and rules/filters in 
Google Mail will be included in the completion notification sent to your 
new Google Mail account.

For more information please visit: http://google.pdx.edu

-PSU Google Project Team
EOS
}

msgSendmail | /usr/lib/sendmail -f no-reply@pdx.edu ${1}@pdx.edu
msg | sendEmail -q -o reply-to=no-reply@pdx.edu -f no-reply@pdx.edu -u 'Your PSU email is about to be migrated to Google Mail' -f no-reply@pdx.edu -t ${1}@odin.pdx.edu -s cyrus.psumail.pdx.edu 