#!/bin/sh

msg(){
cat << EOS
REPLY-To: weekse@pdx.edu
Subject: Your PSU email has been converted to Google Mail  

Your PSU email has been converted to use the new Google PSU mail system.
You will no longer need to check the PSU email system for your incoming email.
Please visit http://mail.pdx.edu to access your mail in the future.

Helpful information can be found at https://sites.google.com/a/pdx.edu/google-apps/email-migration 

EOS
}

msg | /usr/lib/sendmail -f weekse@pdx.edu ${1}@pdx.edu
