#!/bin/sh

msg(){
cat << EOS
REPLY-To: PSU Google Project Team <no-reply@pdx.edu>
Organization: Portland State University
MIME-Version: 1.0
Subject: Congratulations, you have successfully migrated to PSU Google Mail!
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: 7bit

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
  <head>

    <meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">
    <title>Congratulations, the email opt-in process is complete! Read
      on for the next steps...</title>
  </head>
  <body text="#000000" bgcolor="#ffffff">
    <span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
      0); background-color: transparent; font-weight: normal;
      font-style: normal; font-variant: normal; text-decoration: none;
      vertical-align: baseline;"
      id="internal-source-marker_0.5967943486046409">Welcome to the new
      home for your PSU Email! Now that you have converted to Google
      Mail, all messages sent to your @pdx.edu mail address or aliases
      will arrive here and will no longer be delivered to Webmail.
      &nbsp;Mail clients such as Thunderbird, Mac Mail, or Outlook may
      still be used, but they must be reconfigured (see below). Take
      some time to familiarize yourself with the new layout, features,
      interface, and update your bookmarks to point to </span><a
      href="http://mail.pdx.edu"><span style="font-size: 11pt;
        font-family: Arial; color: rgb(0, 0, 153); background-color:
        transparent; font-weight: normal; font-style: normal;
        font-variant: normal; text-decoration: underline;
        vertical-align: baseline;">http://mail.pdx.edu</span></a><span
      style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0);
      background-color: transparent; font-weight: normal; font-style:
      normal; font-variant: normal; text-decoration: none;
      vertical-align: baseline;"> &nbsp;For more information on how to
      use Google Mail, visit the </span><a
href="https://sites.google.com/a/googleapps.com/google-apps-learning-center/gmail"><span
        style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
        153); background-color: transparent; font-weight: normal;
        font-style: normal; font-variant: normal; text-decoration:
        underline; vertical-align: baseline;">google learning center</span></a><span
      style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0);
      background-color: transparent; font-weight: normal; font-style:
      normal; font-variant: normal; text-decoration: none;
      vertical-align: baseline;">.</span><br>
    <span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
      0); background-color: transparent; font-weight: normal;
      font-style: normal; font-variant: normal; text-decoration: none;
      vertical-align: baseline;"></span><br>
    <span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
      0); background-color: transparent; font-weight: normal;
      font-style: normal; font-variant: normal; text-decoration: none;
      vertical-align: baseline;">Your next steps...</span>
    <ol>
      <li style="list-style-type: decimal; font-size: 11pt; font-family:
        Arial; color: rgb(0, 0, 0); background-color: transparent;
        font-weight: normal; font-style: normal; font-variant: normal;
        text-decoration: none; vertical-align: baseline;"><span
          style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
          0); background-color: transparent; font-weight: normal;
          font-style: normal; font-variant: normal; text-decoration:
          none; vertical-align: baseline;">Mail Clients (i.e.
          Thunderbird, Outlook, and iPhone/Android mail apps) will not
          work correctly and will need to be reconfigured to work with
          Google Mail. &nbsp;Before setting up Outlook or Thunderbird we
          encourage you to give the web interface a try, after all you
          are already here. </span></li>
    </ol>
    <br>
    <p dir="ltr" style="margin-left: 36pt; margin-top: 0pt;
      margin-bottom: 0pt;"><span style="font-size: 11pt; font-family:
        Arial; color: rgb(0, 0, 0); background-color: transparent;
        font-weight: normal; font-style: normal; font-variant: normal;
        text-decoration: none; vertical-align: baseline;">More
        information can be found here: </span><a
        href="http://www.oit.pdx.edu/google-mail-client-settings"><span
          style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
          153); background-color: transparent; font-weight: normal;
          font-style: normal; font-variant: normal; text-decoration:
          underline; vertical-align: baseline;">http://www.oit.pdx.edu/google-mail-client-settings</span></a><span
        style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0);
        background-color: transparent; font-weight: normal; font-style:
        normal; font-variant: normal; text-decoration: none;
        vertical-align: baseline;"></span></p>
    <span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
      0); background-color: transparent; font-weight: normal;
      font-style: normal; font-variant: normal; text-decoration: none;
      vertical-align: baseline;"></span>
    <ol start="2">
      <li style="list-style-type: decimal; font-size: 11pt; font-family:
        Arial; color: rgb(0, 0, 0); background-color: transparent;
        font-weight: normal; font-style: normal; font-variant: normal;
        text-decoration: none; vertical-align: baseline;"><span
          style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
          0); background-color: transparent; font-weight: normal;
          font-style: normal; font-variant: normal; text-decoration:
          none; vertical-align: baseline;">Email forwarding configured
          via OAM or Webmail has been disabled (if you were using it),
          and mail filters/rules will need to be created in Gmail. </span></li>
    </ol>
    <br>
    <p dir="ltr" style="margin-left: 36pt; margin-top: 0pt;
      margin-bottom: 0pt;"><span style="font-size: 11pt; font-family:
        Arial; color: rgb(0, 0, 0); background-color: transparent;
        font-weight: normal; font-style: normal; font-variant: normal;
        text-decoration: none; vertical-align: baseline;">More
        information can be found here: </span><a
        href="http://www.oit.pdx.edu/google-mail-filter-settings"><span
          style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
          153); background-color: transparent; font-weight: normal;
          font-style: normal; font-variant: normal; text-decoration:
          underline; vertical-align: baseline;">http://www.oit.pdx.edu/google-mail-filter-settings</span></a><span
        style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0);
        background-color: transparent; font-weight: normal; font-style:
        normal; font-variant: normal; text-decoration: none;
        vertical-align: baseline;"></span></p>
    <span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
      0); background-color: transparent; font-weight: normal;
      font-style: normal; font-variant: normal; text-decoration: none;
      vertical-align: baseline;"></span>
    <ol start="3">
      <li style="list-style-type: decimal; font-size: 11pt; font-family:
        Arial; color: rgb(0, 0, 0); background-color: transparent;
        font-weight: normal; font-style: normal; font-variant: normal;
        text-decoration: none; vertical-align: baseline;"><span
          style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
          0); background-color: transparent; font-weight: normal;
          font-style: normal; font-variant: normal; text-decoration:
          none; vertical-align: baseline;">While the PSU directory is
          integrated into Google Mail, personal contacts may be
          imported, as they were not imported as part of the opt-in
          process. </span></li>
    </ol>
    <br>
    <p dir="ltr" style="margin-left: 36pt; margin-top: 0pt;
      margin-bottom: 0pt;"><span style="font-size: 11pt; font-family:
        Arial; color: rgb(0, 0, 0); background-color: transparent;
        font-weight: normal; font-style: normal; font-variant: normal;
        text-decoration: none; vertical-align: baseline;">More
        information can be found here: </span><a
        href="http://oit.pdx.edu/Contacts-Google"><span
          style="font-size: 10pt; font-family: Arial; color: rgb(0, 0,
          204); background-color: rgb(255, 255, 255); font-weight:
          normal; font-style: normal; font-variant: normal;
          text-decoration: underline; vertical-align: baseline;">http://oit.pdx.edu/Contacts-Google</span></a><span
        style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0);
        background-color: transparent; font-weight: normal; font-style:
        normal; font-variant: normal; text-decoration: none;
        vertical-align: baseline;"></span></p>
    <span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
      0); background-color: transparent; font-weight: normal;
      font-style: normal; font-variant: normal; text-decoration: none;
      vertical-align: baseline;"></span>
    <ol start="4">
      <li style="list-style-type: decimal; font-size: 11pt; font-family:
        Arial; color: rgb(0, 0, 0); background-color: transparent;
        font-weight: normal; font-style: normal; font-variant: normal;
        text-decoration: none; vertical-align: baseline;"><span
          style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
          0); background-color: transparent; font-weight: normal;
          font-style: normal; font-variant: normal; text-decoration:
          none; vertical-align: baseline;">Turning off or adjusting Web
          Clips: </span><a
          href="http://oit.pdx.edu/adujst-webclip-settings"><span
            style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
            153); background-color: transparent; font-weight: normal;
            font-style: normal; font-variant: normal; text-decoration:
            underline; vertical-align: baseline;">http://oit.pdx.edu/adujst-webclip-settings</span></a><span
          style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
          0); background-color: transparent; font-weight: normal;
          font-style: normal; font-variant: normal; text-decoration:
          none; vertical-align: baseline;"></span></li>
    </ol>
    <br>
    <span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
      0); background-color: transparent; font-weight: normal;
      font-style: normal; font-variant: normal; text-decoration: none;
      vertical-align: baseline;"></span>
    <ol start="5">
      <li style="list-style-type: decimal; font-size: 11pt; font-family:
        Arial; color: rgb(0, 0, 0); background-color: transparent;
        font-weight: normal; font-style: normal; font-variant: normal;
        text-decoration: none; vertical-align: baseline;"><span
          style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
          0); background-color: transparent; font-weight: normal;
          font-style: normal; font-variant: normal; text-decoration:
          none; vertical-align: baseline;">Google Mail defaults to a
          threaded conversation view, grouping messages together by
          their subject line. If you would like more information, or how
          to disable it:<br class="kix-line-break">
        </span><a
href="https://mail.google.com/support/bin/answer.py?hl=en&amp;answer=5900"><span
            style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
            153); background-color: transparent; font-weight: normal;
            font-style: normal; font-variant: normal; text-decoration:
            underline; vertical-align: baseline;">https://mail.google.com/support/bin/answer.py?hl=en&amp;answer=5900</span></a><span
          style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
          0); background-color: transparent; font-weight: normal;
          font-style: normal; font-variant: normal; text-decoration:
          none; vertical-align: baseline;"></span></li>
    </ol>
    <br>
    <span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
      0); background-color: transparent; font-weight: normal;
      font-style: normal; font-variant: normal; text-decoration: none;
      vertical-align: baseline;"></span><br>
    <span style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
      0); background-color: transparent; font-weight: normal;
      font-style: normal; font-variant: normal; text-decoration: none;
      vertical-align: baseline;">For more information please visit the
      Google Apps project site: </span><br>
    <a
href="https://sites.google.com/a/pdx.edu/google-apps/email-migration/opt-in-complete"><span
        style="font-size: 11pt; font-family: Arial; color: rgb(0, 0,
        153); background-color: transparent; font-weight: normal;
        font-style: normal; font-variant: normal; text-decoration:
        underline; vertical-align: baseline;">googleapps.pdx.edu/opt-in-complete</span></a><span
      style="font-size: 11pt; font-family: Arial; color: rgb(0, 0, 0);
      background-color: transparent; font-weight: normal; font-style:
      normal; font-variant: normal; text-decoration: none;
      vertical-align: baseline;"></span>
  </body>
</html>
EOS
}

msg | /usr/lib/sendmail -f no-reply@pdx.edu ${1}@pdx.edu
