#!/bin/sh

PATH=$PATH:/vol/goblin/bin

msg(){
cat << EOS
You have successfully migrated to Google Mail! New mail will NOT be delivered to this location. 
Please discontinue using this mailbox for sending or receiving messages. All messages sent to 
your @pdx.edu address will now be delivered to your Google Mail inbox at mail.pdx.edu.

Your next steps...

   1. Login to your Google Mail using mail.pdx.edu to verify your
   mail is working properly.

   2. Mail Clients (i.e. Thunderbird, Outlook, and iPhone/Android mail apps)
   will not work correctly and will need to be reconfigured to work with 
   Google Mail.  Before setting up Outlook or Thunderbird we encourage
   you to give the Google Mail web interface a try at mail.pdx.edu.


   More information can be found here: 
   http://www.oit.pdx.edu/google-mail-client-settings

   3. Email forwarding configured in OAM or Webmail has been disabled (if you were
   using it), and mail filters/rules will need to be re-created in Google Mail.  

   More information can be found here: 
   http://www.oit.pdx.edu/google-mail-filter-settings

   4. While the PSU directory is integrated into Google Mail, personal
   contacts may be imported, as they were not imported as part of the 
   opt-in process. 

   More information can be found here: http://oit.pdx.edu/Contacts-Google

For more information please visit the Google Apps project site: 
https://sites.google.com/a/pdx.edu/google-apps/email-migration/opt-in-complete
EOS
}

msg | sendEmail -q -o reply-to=no-reply@pdx.edu -f no-reply@pdx.edu -u 'Email Migration Complete! Use Google Mail @  http://mail.pdx.edu' -f no-reply@pdx.edu -t ${1}@odin.pdx.edu -s cyrus.psumail.pdx.edu 
